# Generated by Django 3.2.18 on 2023-11-17 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocMedPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FNAME', models.CharField(max_length=30)),
                ('LNAME', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MEDNAME', models.CharField(max_length=40)),
                ('QUANTITY', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FNAME', models.CharField(max_length=30)),
                ('LNAME', models.CharField(max_length=30)),
                ('CARD_EXPIRY_DATE', models.DateField()),
                ('Doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor_app.doctor')),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USED', models.CharField(max_length=1)),
                ('EXPIRYDATE', models.DateField()),
                ('Doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor_app.doctor')),
                ('Patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor_app.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SPECNAME', models.CharField(max_length=50)),
                ('SPECSDESC', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ReceiptMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DocMedPermission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor_app.docmedpermission')),
                ('Receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor_app.receipt')),
            ],
        ),
        migrations.CreateModel(
            name='MedForSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor_app.medication')),
                ('Specialization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor_app.specialization')),
            ],
        ),
        migrations.CreateModel(
            name='HasMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QUANTITY', models.IntegerField()),
                ('Medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor_app.medication')),
                ('Pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor_app.pharmacy')),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='Specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor_app.specialization'),
        ),
        migrations.AddField(
            model_name='docmedpermission',
            name='Doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor_app.doctor'),
        ),
        migrations.AddField(
            model_name='docmedpermission',
            name='MedForSpec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor_app.medforspec'),
        ),
        migrations.AddField(
            model_name='docmedpermission',
            name='Medication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor_app.medication'),
        ),
    ]
