# Generated by Django 3.2.18 on 2023-11-17 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='PHARNAME',
            field=models.CharField(default='Benu', max_length=50),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='FNAME',
            field=models.CharField(max_length=30, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='LNAME',
            field=models.CharField(max_length=30, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='hasmedication',
            name='QUANTITY',
            field=models.IntegerField(verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='MEDNAME',
            field=models.CharField(max_length=40, verbose_name='Medication Name'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='FNAME',
            field=models.CharField(max_length=30, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='LNAME',
            field=models.CharField(max_length=30, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='EXPIRYDATE',
            field=models.DateField(verbose_name='Expiry Date'),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='USED',
            field=models.CharField(default='N', max_length=1, verbose_name='Used'),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='SPECNAME',
            field=models.CharField(max_length=50, verbose_name='Specialization'),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='SPECSDESC',
            field=models.CharField(max_length=100, verbose_name='Description'),
        ),
    ]
