# Generated by Django 3.2.18 on 2023-11-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_app', '0002_auto_20231117_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiptmedication',
            name='PERIOD',
            field=models.IntegerField(default=12, verbose_name='Period of medication taking'),
        ),
    ]
